server:
  port: 8082

spring:
  application:
    name: vault-event-service
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true
    consumer:
      group-id: cloudvault-event-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.cloudvault.event.model,com.cloudvault.event.dto"

cloudvault:
  kafka:
    topics:
      file-events: file-vault-events
      dlq-events: file-vault-events.DLQ
    retry:
      max-attempts: 3
      backoff-ms: 1000
